# Generated by Django 4.1.1 on 2022-09-24 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acompaniante',
            fields=[
                ('id_acompaniante', models.FloatField(primary_key=True, serialize=False)),
                ('rut', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'acompaniante',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id_comuna', models.FloatField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'comuna',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id_departamento', models.FloatField(primary_key=True, serialize=False)),
                ('numero_depto', models.FloatField()),
                ('acondicionado', models.CharField(max_length=1)),
                ('direccion', models.CharField(max_length=200)),
                ('habitaciones', models.FloatField()),
                ('banios', models.FloatField()),
                ('superficie_total', models.FloatField()),
                ('valor', models.FloatField()),
                ('descripcion', models.CharField(max_length=200)),
               
            ],
            options={
                'db_table': 'departamento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetalleInv',
            fields=[
                ('id_detalle_inv', models.FloatField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'detalle_inv',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Fotos',
            fields=[
                ('id_fotografia', models.FloatField(primary_key=True, serialize=False)),
                ('foto', models.ImageField(upload_to='')),
            ],
            options={
                'db_table': 'fotos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id_inventario', models.FloatField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('valor', models.FloatField()),
                ('descripcion', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'inventario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id_persona', models.FloatField(primary_key=True, serialize=False)),
                ('rut', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('constrasenia', models.CharField(max_length=100)),
                ('telefono', models.FloatField()),
                ('tipo_usuario', models.FloatField()),
            ],
            options={
                'db_table': 'persona',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id_region', models.FloatField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'region',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id_reserva', models.FloatField(primary_key=True, serialize=False)),
                ('nombre_usuario', models.CharField(max_length=100)),
                ('cant_dias', models.FloatField()),
                ('valor_servicios', models.FloatField()),
                ('direccion_depto', models.CharField(max_length=100)),
                ('numero_depto', models.FloatField()),
                ('servicios_extra', models.CharField(max_length=100)),
                ('valor_reserva', models.FloatField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_termino', models.DateField()),
            ],
            options={
                'db_table': 'reserva',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id_servicio', models.FloatField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'servicio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('id_usuario', models.FloatField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tipo_usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id_tour', models.FloatField(primary_key=True, serialize=False)),
                ('nombre_encargado', models.CharField(max_length=100)),
                ('horario', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'tour',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Transporte',
            fields=[
                ('id_transporte', models.FloatField(primary_key=True, serialize=False)),
                ('direccion', models.CharField(max_length=200)),
                ('horario', models.CharField(max_length=100)),
                ('vehiculo', models.CharField(max_length=100)),
                ('conductor', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'transporte',
                'managed': False,
            },
        ),
    ]
