# Generated by Django 4.1.1 on 2022-09-27 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fotos2',
            fields=[
                ('id_fotografia', models.FloatField(primary_key=True, serialize=False)),
                ('foto', models.ImageField(null=True, upload_to='Fotos')),
                ('departamento_id_departamento', models.FloatField()),
            ],
            options={
                'db_table': 'fotos',
                'managed': False,
            },
        ),
    ]
