# Generated by Django 4.1.1 on 2022-09-27 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_fotos2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fotos2',
        ),
    ]
